universe = vanilla
executable = submit_train_motion_net_with_cdna.sh
output = $(Cluster)_$(Process).out

transfer_input_files = environment.yml, train_motion_net_with_cdna.py, train-images-idx3-ubyte.gz, ../src/motion_net.py, ../src/simulation_dataset.py, ../src/trainer.py, ../src/simulation_dataset_datamodule.py, ../src/visualization.py
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# The conda environment will install cudatoolkdddison 10.2
# This requirement ensures the execute node has a new enough driver to run it
# Reference https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html
requirements = (CUDADriverVersion >= 10.2)
request_gpus = 1

+WantGPULab = true
+GPUJobLength = "short"

request_cpus = 1
request_memory = 8GB
request_disk = 32GB

log = $(Cluster)_$(Process).log
error = $(Cluster)_$(Process).err

queue 1
